os: Visual Studio 2015

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cmd: >-
      build.cmd /t:configure
      
      build.cmd %BuildArgs%
      
      .nuget\packages\coveralls.io\tools\coveralls.net.exe --opencover out\coverage.xml

# we run the tests ourselves in build.cmd for coverage
test: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: l3O4lbgUscsMKm9M580fsx0rBDal/nTrtRTt3ZE6897ps9Q3USzEIwR254Z4CfKv

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      branch: /(master|cycle9)

nuget:
  project_feed: true
  
artifacts:
  - path: out\*.nupkg
    name: Package
